title: YongZSæ°¸å€¼ç”Ÿ's personal weblog
description:æ‚¨å¥½ / Hello / Hallo / ã“ã‚“ã«ã¡ã¯ / å€å˜² Xin chÃ o / ĞŸÑ€Ğ¸Ğ²ĞµÑ‚ / à½–à½€à¾²à¼‹à½¤à½²à½¦à¼‹à½–à½‘à½ºà¼‹à½£à½ºà½‚à½¦à¼
  - ğŸ“Chinese Mainland, HÃ n Chinese
  - Music production enthusiast, travelling & photography lover, Iâ€™ll post my daily life here.
theme: minima
plugins:
  - jekyll-feed
